### ISSUE TITLE
storage node error logs, this happened after i restart my validator node which is used for storage node

### ISSUE THREAD

**Issue by hubofvalley** [0glabs/0g-storage-node#165]
``ERROR task_executor: Task panic. This is a bug! task_name="pruner" <none> advice="Please check above for a backtrace and notify the developers"``

**Comment by hubofvalley** [comment]
actually, it can be solved by delete the ``db`` and ``network`` folder then resync from the scratch. but it's really annoying tho

**Comment by 0g-peterzhb** [comment]
It's probably that your storage node was at a old version. For storage node, we upgraded a few times on the testnet and some are not backward compatible. So has to delete the db folder to restart. They were announced in the discord channel.
