### ISSUE TITLE
Version info is not correct

### ISSUE THREAD

**Issue by qyeah98** [0glabs/0g-storage-node#69]
1. Problem
v0.2.0 binary version is old one.

**Command**
``` bash
zgs_node --version
```

**Result**
```bash
zgs_node 0.1.0
```
it should be `0.2.0`

2. Environment
OS: Ubuntu22.04LTS
cargo 1.78.0 (54d8815d0 2024-03-26)
rustc 1.78.0 (9b00956e5 2024-04-29)
rustup 1.27.1 (54dd3d00f 2024-04-24)

**Comment by qyeah98** [comment]
I believe edit `version = "0.2.0"` at `run/Cargo.toml`

**Comment by nodebrand** [comment]
same agree

**Comment by qyeah98** [comment]
Solved new binary.

```
zgs_node --version
zgs_node 0.2.0
```
